title: Cérele — Hospedagem e otimização de sites de notícias
description: Agência web especializada em sites de notícias
url: "https://celere.dev"

markdown: kramdown

exclude:
- README.md
- LICENSE.md